openapi: 3.1.0
info:
  title: API Wallet
  version: "1.0"
paths:
  /api/credits:
    post:
      summary: Crediter un numero
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                amount:
                  type: integer
                timestamp:
                  type: string
                raw_sms:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
  /wallet/{phone}:
    get:
      summary: Obtenir le solde
      parameters:
        - in: path
          name: phone
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: integer
  /healthz:
    get:
      summary: Sante du service
      responses:
        '200':
          description: OK
