name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
        working-directory: android-client
      - run: flutter test
        working-directory: android-client
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test ./...
        working-directory: wallet-plugin-go
